name: Java build

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    uses: valitydev/java-workflow/.github/workflows/maven-thrift-build.yml@719d11e63d9fab9d3299f0c8d74db1f8637431a5 # v2
